[agent]
  interval = "5s" # High frequency for live testing
  flush_interval = "5s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUXDB_TOKEN"
  organization = "$INFLUXDB_ORG"
  bucket = "$INFLUXDB_BUCKET"

[[inputs.mock]]
  ## Set the metric name to use for reporting
  metric_name = "mock"

[[inputs.mock.sine_wave]]
  ## Measure name
  name = "sine_wave"
  amplitude = 1.0
  period = 0.5
  phase = 20.0
  base_line = 0.0

[[inputs.cpu]]
  percpu = false
  totalcpu = true